# Generated by Django 4.0.3 on 2022-04-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
